spring.application.name=zechify
spring.datasource.url=jdbc:postgresql://localhost:5432/zechify
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=update
server.address=0.0.0.0
server.port:8080